<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-MC9GRJJ" name="com.tricentis.sampleapp.Test.Test1" tests="4" failures="1" timestamp="2020-12-31T01:04:39 IST" time="56.775" errors="0">
  <testcase name="TestCase" time="0.179" classname="com.tricentis.sampleapp.Test.Test1">
    <skipped/>
  </testcase> <!-- TestCase -->
  <system-out/>
  <testcase name="TestCase" time="0.010" classname="com.tricentis.sampleapp.Test.Test1">
    <skipped/>
  </testcase> <!-- TestCase -->
  <system-out/>
  <testcase name="TestCase" time="0.012" classname="com.tricentis.sampleapp.Test.Test1">
    <skipped/>
  </testcase> <!-- TestCase -->
  <system-out/>
  <testcase name="TestCase" time="56.574" classname="com.tricentis.sampleapp.Test.Test1">
    <failure type="java.lang.AssertionError" message="expected [FirstName] but found [First Name]">
      <![CDATA[java.lang.AssertionError: expected [FirstName] but found [First Name]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.tricentis.sampleapp.Utilities.ActionEngine.assertEqualsString_custom(ActionEngine.java:173)
at com.tricentis.sampleapp.TestEngine.KeywordEngine.locatorAction(KeywordEngine.java:163)
at com.tricentis.sampleapp.TestEngine.KeywordEngine.startExecution(KeywordEngine.java:101)
at com.tricentis.sampleapp.Test.Test1.TestCase(Test1.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase -->
  <system-out/>
</testsuite> <!-- com.tricentis.sampleapp.Test.Test1 -->
